version: '3'

services:
  web:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=appsec_labs

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=appsec_labs
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 